FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY target/PhotoAppApiZuulGateway-0.0.1-SNAPSHOT.jar ZuulApiGateway.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","ZuulApiGateway.jar"]